### ISSUE TITLE
Reply to inquiry from Associated Press

### ISSUE THREAD

**Issue by 2041876935** [calpirateparty/CAPP#11]
CAPP VP Jorge Morales has received an e-mail inquiry from the AP. We are using this Issue to craft a response by Noon tomorrow.

Please contribute to the response using the below Etherpad:
(https://pad.calpirateparty.org/p/AP_response)

**Comment by tjcrowley** [comment]
If they need a quote from a registered pirate in SF I am available at darren@kinkbnb.com

**Comment by tjcrowley** [comment]
It would also help to see their inquiry directly. Can you share that email?

**Comment by sptankard** [comment]
We're checking with the sender first before publishing their message verbatim. We'll give a paraphrase in more detail in the next few minutes.

On April 27, 2017 2:59:43 PM PDT, Darren Mckeeman <notifications@github.com> wrote:
>It would also help to see their inquiry directly. Can you share that
>email? 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/calpirateparty/CAPP/issues/11#issuecomment-297851047

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lolkje** [comment]
I would leave out the phrase about Sanders. It could give a mistaken impression that Pirates are far left. I wrote my suggestion for what to say instead on the Pad.

**Comment by 2041876935** [comment]
So unfortunately the journalist that reached out to us was on a deadline (less than an hour). A rushed generic response was served via email (shared below):

`The California Pirate Party was reformed following this past November's Presidential Election. We are a small group of volunteers intent on bringing the larger Pirate Movement to California and strengthening the Pirate Party throughout the United States. We are pleased at the success of the Massachusetts Pirate Party and encouraged by the amount of attention their Events Calendar has been receiving as of late. We have our own events planned for the near future and have begun organizing volunteers towards those ends. Since the Pirate Party is a non-traditional political movement we actually encourage citizen participation in all aspects of the party, from event planning, to platform discussions, or even answering email inquiries from the press. Anyone can get directly involved with nothing more than an internet connection.

You can learn more about us at our website: https://www.calpirateparty.org

But for some short bullet about where we stand, please refer to our Wiki: https://wiki.calpirateparty.org/Platform_bullet_points

Given the current political landscape we feel America is well overdue for a viable 3rd party. The Pirate Party has experienced mild success abroad, but with such strong efforts coming out of Massachusetts and California we feel it is time for the broader Pirate movement to gain a foothold in America.

Thank you for your time, please do not hesitate to follow up with us at any time.`
