### ISSUE TITLE
Complete re-elevation/accession to PNC

### ISSUE THREAD

**Issue by sptankard** [calpirateparty/CAPP#2]
Complete CAPP's re-elevation/accession to the USPP's Pirate National Committee (PNC), so that California is represented with the national party.

**Comment by AaronBurrSir** [comment]
Correct me if I'm wrong, but wasn't this already completed? Just wondering what is left for this to be considered "complete".

**Comment by sptankard** [comment]
The PNC has not yet voted to accept CAPP's re-elevation. They still need to do so for it to be formally complete...

**Comment by 2041876935** [comment]
Is this really an Issue for "us" though? Perhaps we should consider this **Closed** because there is nothing more "we" need to do?

**Comment by sptankard** [comment]
Ok, PNC voted this evening to re-elevate CAPP. We are now an official, voting member of USPP :)

See here: https://pnc.piratenpad.de/ep/pad/view/ro.75Z6hFFQ6miTAKznaf/rev.201
