### ISSUE TITLE
Create a Step By Step Guide for Setting up and Using Signal

### ISSUE THREAD

**Issue by AaronBurrSir** [calpirateparty/CAPP#5]
This is 100% based on my difficulties with using Signal. I actually tend to consider myself as having a high literacy of technical things and computer use in general, but even Signal left me confused or shaking my head at moments. 

If I'm having trouble with it and I consider myself somewhat computer literate, you know for sure that other people are going to have a lot more problems with it.

**Comment by sptankard** [comment]
How do you find these guides?

https://ssd.eff.org/en/module/how-use-signal-android
https://ssd.eff.org/en/module/how-use-signal-ios

**Comment by AaronBurrSir** [comment]
Those look great! We will for sure want those linked on the CAPP website and on the wiki. Basically we just need a wiki entry for Signal that can contain links to both guides and a short description on what signal is and why we should use it.

**Comment by sptankard** [comment]
I've been meaning to put that together as a section of the tech use guide!

**Comment by sptankard** [comment]
https://wiki.calpirateparty.org/Infosec_policy#Signal_Private_Messenger

**Comment by 2041876935** [comment]
I am Merging this Issue with (https://github.com/calpirateparty/CAPP/issues/9)
